### ISSUE TITLE
Error when logging into the application

### ISSUE THREAD

**Issue by bbenz** [Azure-Samples/containerize-and-deploy-Java-app-to-Azure#1]
The issue occurs in step 6-Deploy (https://docs.microsoft.com/en-us/learn/modules/containerize-deploy-java-app-aks/6-deploy) of this learn module - https://docs.microsoft.com/en-us/learn/modules/containerize-deploy-java-app-aks/

When signing into the deployed application with any user from tomcat-users.xml for example someuser@azure.com: password, you get an error that indicates that the container is out of memory.   

The likely solution is that we need to add memory limits to the dockerfile.  There are none specified now.  

The steps to recreate were recorded at the 0:47:00 mark in this live broadcast : https://docs.microsoft.com/en-us/shows/learn-live/deploy-apps-java-azure-ep01-containerize-deploy-java-app-azure?WT.mc_id=learnlive-20220321B

![image](https://user-images.githubusercontent.com/2809036/160909835-1cd2e372-f51d-47e8-9877-5179ef304347.png)

**Comment by chtrembl** [comment]
Hi @bbenz, thanks for pointing this out. I just addressed this in the latest commit, someuser@azure.com was missing required meta data from the db, hence the NullPointerException. Please do a pull on your fork and rebuild the docker image and redeploy.

**Comment by chtrembl** [comment]
Hi @bbenz, thanks for pointing this out. I just addressed this in the latest commit, [someuser@azure.com](mailto:someuser@azure.com) was missing required meta data from the db, hence the NullPointerException. Please do a pull on your fork and rebuild the docker image and redeploy.

**Comment by chtrembl** [comment]
Hi @bbenz, thanks for pointing this out. I just addressed this in the latest commit, [someuser@azure.com](mailto:someuser@azure.com) was missing required meta data from the db, hence the NullPointerException. Please do a pull on your fork and rebuild the docker image and redeploy.
